/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppUsersRouteImport } from './routes/app/users'
import { Route as AppProductsRouteImport } from './routes/app/products'
import { Route as AppPrioritiesRouteImport } from './routes/app/priorities'
import { Route as AppPartnersRouteImport } from './routes/app/partners'
import { Route as AppOrderRouteImport } from './routes/app/order'
import { Route as AppEvolutionRouteImport } from './routes/app/evolution'
import { Route as AppCompaniesRouteImport } from './routes/app/companies'
import { Route as AppChatRouteImport } from './routes/app/chat'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AppProductsIndexRouteImport } from './routes/app/products/index'
import { Route as AppOrderIndexRouteImport } from './routes/app/order/index'
import { Route as AppVivoExampleRouteImport } from './routes/app/vivo/example'
import { Route as AppTimExampleRouteImport } from './routes/app/tim/example'
import { Route as AppClaroExampleRouteImport } from './routes/app/claro/example'
import { Route as AppProductsModelIndexRouteImport } from './routes/app/products/$model/index'
import { Route as AppOrderModelIndexRouteImport } from './routes/app/order/$model/index'
import { Route as AppProductsModelCategoryRouteImport } from './routes/app/products/$model.$category'
import { Route as AppOrderModelCategoryRouteImport } from './routes/app/order/$model.$category'
import { Route as AppOrderModelCategoryClientTypeRouteImport } from './routes/app/order/$model.$category.$clientType'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsRoute = AppProductsRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPrioritiesRoute = AppPrioritiesRouteImport.update({
  id: '/priorities',
  path: '/priorities',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppPartnersRoute = AppPartnersRouteImport.update({
  id: '/partners',
  path: '/partners',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppOrderRoute = AppOrderRouteImport.update({
  id: '/order',
  path: '/order',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppEvolutionRoute = AppEvolutionRouteImport.update({
  id: '/evolution',
  path: '/evolution',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppCompaniesRoute = AppCompaniesRouteImport.update({
  id: '/companies',
  path: '/companies',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppProductsIndexRoute = AppProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppOrderIndexRoute = AppOrderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppOrderRoute,
} as any)
const AppVivoExampleRoute = AppVivoExampleRouteImport.update({
  id: '/vivo/example',
  path: '/vivo/example',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppTimExampleRoute = AppTimExampleRouteImport.update({
  id: '/tim/example',
  path: '/tim/example',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppClaroExampleRoute = AppClaroExampleRouteImport.update({
  id: '/claro/example',
  path: '/claro/example',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppProductsModelIndexRoute = AppProductsModelIndexRouteImport.update({
  id: '/$model/',
  path: '/$model/',
  getParentRoute: () => AppProductsRoute,
} as any)
const AppOrderModelIndexRoute = AppOrderModelIndexRouteImport.update({
  id: '/$model/',
  path: '/$model/',
  getParentRoute: () => AppOrderRoute,
} as any)
const AppProductsModelCategoryRoute =
  AppProductsModelCategoryRouteImport.update({
    id: '/$model/$category',
    path: '/$model/$category',
    getParentRoute: () => AppProductsRoute,
  } as any)
const AppOrderModelCategoryRoute = AppOrderModelCategoryRouteImport.update({
  id: '/$model/$category',
  path: '/$model/$category',
  getParentRoute: () => AppOrderRoute,
} as any)
const AppOrderModelCategoryClientTypeRoute =
  AppOrderModelCategoryClientTypeRouteImport.update({
    id: '/$clientType',
    path: '/$clientType',
    getParentRoute: () => AppOrderModelCategoryRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/app/chat': typeof AppChatRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/order': typeof AppOrderRouteWithChildren
  '/app/partners': typeof AppPartnersRoute
  '/app/priorities': typeof AppPrioritiesRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/claro/example': typeof AppClaroExampleRoute
  '/app/tim/example': typeof AppTimExampleRoute
  '/app/vivo/example': typeof AppVivoExampleRoute
  '/app/order/': typeof AppOrderIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/order/$model/$category': typeof AppOrderModelCategoryRouteWithChildren
  '/app/products/$model/$category': typeof AppProductsModelCategoryRoute
  '/app/order/$model/': typeof AppOrderModelIndexRoute
  '/app/products/$model/': typeof AppProductsModelIndexRoute
  '/app/order/$model/$category/$clientType': typeof AppOrderModelCategoryClientTypeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/app/chat': typeof AppChatRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/partners': typeof AppPartnersRoute
  '/app/priorities': typeof AppPrioritiesRoute
  '/app/users': typeof AppUsersRoute
  '/app': typeof AppIndexRoute
  '/app/claro/example': typeof AppClaroExampleRoute
  '/app/tim/example': typeof AppTimExampleRoute
  '/app/vivo/example': typeof AppVivoExampleRoute
  '/app/order': typeof AppOrderIndexRoute
  '/app/products': typeof AppProductsIndexRoute
  '/app/order/$model/$category': typeof AppOrderModelCategoryRouteWithChildren
  '/app/products/$model/$category': typeof AppProductsModelCategoryRoute
  '/app/order/$model': typeof AppOrderModelIndexRoute
  '/app/products/$model': typeof AppProductsModelIndexRoute
  '/app/order/$model/$category/$clientType': typeof AppOrderModelCategoryClientTypeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/app/chat': typeof AppChatRoute
  '/app/companies': typeof AppCompaniesRoute
  '/app/evolution': typeof AppEvolutionRoute
  '/app/order': typeof AppOrderRouteWithChildren
  '/app/partners': typeof AppPartnersRoute
  '/app/priorities': typeof AppPrioritiesRoute
  '/app/products': typeof AppProductsRouteWithChildren
  '/app/users': typeof AppUsersRoute
  '/app/': typeof AppIndexRoute
  '/app/claro/example': typeof AppClaroExampleRoute
  '/app/tim/example': typeof AppTimExampleRoute
  '/app/vivo/example': typeof AppVivoExampleRoute
  '/app/order/': typeof AppOrderIndexRoute
  '/app/products/': typeof AppProductsIndexRoute
  '/app/order/$model/$category': typeof AppOrderModelCategoryRouteWithChildren
  '/app/products/$model/$category': typeof AppProductsModelCategoryRoute
  '/app/order/$model/': typeof AppOrderModelIndexRoute
  '/app/products/$model/': typeof AppProductsModelIndexRoute
  '/app/order/$model/$category/$clientType': typeof AppOrderModelCategoryClientTypeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/login'
    | '/app/chat'
    | '/app/companies'
    | '/app/evolution'
    | '/app/order'
    | '/app/partners'
    | '/app/priorities'
    | '/app/products'
    | '/app/users'
    | '/app/'
    | '/app/claro/example'
    | '/app/tim/example'
    | '/app/vivo/example'
    | '/app/order/'
    | '/app/products/'
    | '/app/order/$model/$category'
    | '/app/products/$model/$category'
    | '/app/order/$model/'
    | '/app/products/$model/'
    | '/app/order/$model/$category/$clientType'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/app/chat'
    | '/app/companies'
    | '/app/evolution'
    | '/app/partners'
    | '/app/priorities'
    | '/app/users'
    | '/app'
    | '/app/claro/example'
    | '/app/tim/example'
    | '/app/vivo/example'
    | '/app/order'
    | '/app/products'
    | '/app/order/$model/$category'
    | '/app/products/$model/$category'
    | '/app/order/$model'
    | '/app/products/$model'
    | '/app/order/$model/$category/$clientType'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/(auth)/login'
    | '/app/chat'
    | '/app/companies'
    | '/app/evolution'
    | '/app/order'
    | '/app/partners'
    | '/app/priorities'
    | '/app/products'
    | '/app/users'
    | '/app/'
    | '/app/claro/example'
    | '/app/tim/example'
    | '/app/vivo/example'
    | '/app/order/'
    | '/app/products/'
    | '/app/order/$model/$category'
    | '/app/products/$model/$category'
    | '/app/order/$model/'
    | '/app/products/$model/'
    | '/app/order/$model/$category/$clientType'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/users': {
      id: '/app/users'
      path: '/users'
      fullPath: '/app/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products': {
      id: '/app/products'
      path: '/products'
      fullPath: '/app/products'
      preLoaderRoute: typeof AppProductsRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/priorities': {
      id: '/app/priorities'
      path: '/priorities'
      fullPath: '/app/priorities'
      preLoaderRoute: typeof AppPrioritiesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/partners': {
      id: '/app/partners'
      path: '/partners'
      fullPath: '/app/partners'
      preLoaderRoute: typeof AppPartnersRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/order': {
      id: '/app/order'
      path: '/order'
      fullPath: '/app/order'
      preLoaderRoute: typeof AppOrderRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/evolution': {
      id: '/app/evolution'
      path: '/evolution'
      fullPath: '/app/evolution'
      preLoaderRoute: typeof AppEvolutionRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/companies': {
      id: '/app/companies'
      path: '/companies'
      fullPath: '/app/companies'
      preLoaderRoute: typeof AppCompaniesRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/chat': {
      id: '/app/chat'
      path: '/chat'
      fullPath: '/app/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/products/': {
      id: '/app/products/'
      path: '/'
      fullPath: '/app/products/'
      preLoaderRoute: typeof AppProductsIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/app/order/': {
      id: '/app/order/'
      path: '/'
      fullPath: '/app/order/'
      preLoaderRoute: typeof AppOrderIndexRouteImport
      parentRoute: typeof AppOrderRoute
    }
    '/app/vivo/example': {
      id: '/app/vivo/example'
      path: '/vivo/example'
      fullPath: '/app/vivo/example'
      preLoaderRoute: typeof AppVivoExampleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/tim/example': {
      id: '/app/tim/example'
      path: '/tim/example'
      fullPath: '/app/tim/example'
      preLoaderRoute: typeof AppTimExampleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/claro/example': {
      id: '/app/claro/example'
      path: '/claro/example'
      fullPath: '/app/claro/example'
      preLoaderRoute: typeof AppClaroExampleRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/products/$model/': {
      id: '/app/products/$model/'
      path: '/$model'
      fullPath: '/app/products/$model/'
      preLoaderRoute: typeof AppProductsModelIndexRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/app/order/$model/': {
      id: '/app/order/$model/'
      path: '/$model'
      fullPath: '/app/order/$model/'
      preLoaderRoute: typeof AppOrderModelIndexRouteImport
      parentRoute: typeof AppOrderRoute
    }
    '/app/products/$model/$category': {
      id: '/app/products/$model/$category'
      path: '/$model/$category'
      fullPath: '/app/products/$model/$category'
      preLoaderRoute: typeof AppProductsModelCategoryRouteImport
      parentRoute: typeof AppProductsRoute
    }
    '/app/order/$model/$category': {
      id: '/app/order/$model/$category'
      path: '/$model/$category'
      fullPath: '/app/order/$model/$category'
      preLoaderRoute: typeof AppOrderModelCategoryRouteImport
      parentRoute: typeof AppOrderRoute
    }
    '/app/order/$model/$category/$clientType': {
      id: '/app/order/$model/$category/$clientType'
      path: '/$clientType'
      fullPath: '/app/order/$model/$category/$clientType'
      preLoaderRoute: typeof AppOrderModelCategoryClientTypeRouteImport
      parentRoute: typeof AppOrderModelCategoryRoute
    }
  }
}

interface AppOrderModelCategoryRouteChildren {
  AppOrderModelCategoryClientTypeRoute: typeof AppOrderModelCategoryClientTypeRoute
}

const AppOrderModelCategoryRouteChildren: AppOrderModelCategoryRouteChildren = {
  AppOrderModelCategoryClientTypeRoute: AppOrderModelCategoryClientTypeRoute,
}

const AppOrderModelCategoryRouteWithChildren =
  AppOrderModelCategoryRoute._addFileChildren(
    AppOrderModelCategoryRouteChildren,
  )

interface AppOrderRouteChildren {
  AppOrderIndexRoute: typeof AppOrderIndexRoute
  AppOrderModelCategoryRoute: typeof AppOrderModelCategoryRouteWithChildren
  AppOrderModelIndexRoute: typeof AppOrderModelIndexRoute
}

const AppOrderRouteChildren: AppOrderRouteChildren = {
  AppOrderIndexRoute: AppOrderIndexRoute,
  AppOrderModelCategoryRoute: AppOrderModelCategoryRouteWithChildren,
  AppOrderModelIndexRoute: AppOrderModelIndexRoute,
}

const AppOrderRouteWithChildren = AppOrderRoute._addFileChildren(
  AppOrderRouteChildren,
)

interface AppProductsRouteChildren {
  AppProductsIndexRoute: typeof AppProductsIndexRoute
  AppProductsModelCategoryRoute: typeof AppProductsModelCategoryRoute
  AppProductsModelIndexRoute: typeof AppProductsModelIndexRoute
}

const AppProductsRouteChildren: AppProductsRouteChildren = {
  AppProductsIndexRoute: AppProductsIndexRoute,
  AppProductsModelCategoryRoute: AppProductsModelCategoryRoute,
  AppProductsModelIndexRoute: AppProductsModelIndexRoute,
}

const AppProductsRouteWithChildren = AppProductsRoute._addFileChildren(
  AppProductsRouteChildren,
)

interface AppRouteRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppCompaniesRoute: typeof AppCompaniesRoute
  AppEvolutionRoute: typeof AppEvolutionRoute
  AppOrderRoute: typeof AppOrderRouteWithChildren
  AppPartnersRoute: typeof AppPartnersRoute
  AppPrioritiesRoute: typeof AppPrioritiesRoute
  AppProductsRoute: typeof AppProductsRouteWithChildren
  AppUsersRoute: typeof AppUsersRoute
  AppIndexRoute: typeof AppIndexRoute
  AppClaroExampleRoute: typeof AppClaroExampleRoute
  AppTimExampleRoute: typeof AppTimExampleRoute
  AppVivoExampleRoute: typeof AppVivoExampleRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppCompaniesRoute: AppCompaniesRoute,
  AppEvolutionRoute: AppEvolutionRoute,
  AppOrderRoute: AppOrderRouteWithChildren,
  AppPartnersRoute: AppPartnersRoute,
  AppPrioritiesRoute: AppPrioritiesRoute,
  AppProductsRoute: AppProductsRouteWithChildren,
  AppUsersRoute: AppUsersRoute,
  AppIndexRoute: AppIndexRoute,
  AppClaroExampleRoute: AppClaroExampleRoute,
  AppTimExampleRoute: AppTimExampleRoute,
  AppVivoExampleRoute: AppVivoExampleRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
